spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6432/warehouse"
    username: "warehouse"
    password: "warehouse"

server:
  port: 0