spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6432/shopping_store"
    username: "shoppingstore"
    password: "shoppingstore"

server:
  port: 0